
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
        '--file', 'Dockerfile.gcloud',
        '--tag', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA',
        '--tag', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:${_VERSION}',
        '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:${_VERSION}']
images: [
  'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA',
  'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:${_VERSION}'
]
